export const currencyOptions = [
    { value: "USD", label: "United States Dollar ($)" },
    { value: "EUR", label: "Euro (€)" },
    { value: "JPY", label: "Japanese Yen (¥)" },
    { value: "GBP", label: "British Pound (£)" },
    { value: "AUD", label: "Australian Dollar (A$)" },
    { value: "CAD", label: "Canadian Dollar (C$)" },
    { value: "CHF", label: "Swiss Franc (CHF)" },
    { value: "CNY", label: "Chinese Yuan (¥)" },
    { value: "SEK", label: "Swedish Krona (SEK)" },
    { value: "NZD", label: "New Zealand Dollar (NZ$)" },
    { value: "AED", label: "United Arab Emirates Dirham (AED)" },
    { value: "AFN", label: "Afghan Afghani (Af)" },
    { value: "ALL", label: "Albanian Lek (ALL)" },
    { value: "AMD", label: "Armenian Dram (AMD)" },
    { value: "ANG", label: "Netherlands Antillean Guilder (ANG)" },
    { value: "AOA", label: "Angolan Kwanza (AOA)" },
    { value: "ARS", label: "Argentine Peso (ARS)" },
    { value: "AZN", label: "Azerbaijani Manat (AZN)" },
    { value: "BAM", label: "Bosnia and Herzegovina Convertible Mark (BAM)" },
    { value: "BDT", label: "Bangladeshi Taka (৳)" },
    { value: "BGN", label: "Bulgarian Lev (BGN)" },
    { value: "BHD", label: "Bahraini Dinar (BHD)" },
    { value: "BIF", label: "Burundian Franc (BIF)" },
    { value: "BND", label: "Brunei Dollar (BND)" },
    { value: "BOB", label: "Bolivian Boliviano (BOB)" },
    { value: "BRL", label: "Brazilian Real (R$)" },
    { value: "BSD", label: "Bahamian Dollar (BSD)" },
    { value: "BTN", label: "Bhutanese Ngultrum (BTN)" },
    { value: "BWP", label: "Botswana Pula (BWP)" },
    { value: "BYN", label: "Belarusian Ruble (BYN)" },
    { value: "BZD", label: "Belize Dollar (BZD)" },
    { value: "CDF", label: "Congolese Franc (CDF)" },
    { value: "CLP", label: "Chilean Peso (CLP)" },
    { value: "COP", label: "Colombian Peso (COP)" },
    { value: "CRC", label: "Costa Rican Colón (CRC)" },
    { value: "CUP", label: "Cuban Peso (CUP)" },
    { value: "CZK", label: "Czech Koruna (CZK)" },
    { value: "DJF", label: "Djiboutian Franc (DJF)" },
    { value: "DKK", label: "Danish Krone (DKK)" },
    { value: "DOP", label: "Dominican Peso (DOP)" },
    { value: "DZD", label: "Algerian Dinar (DZD)" },
    { value: "EGP", label: "Egyptian Pound (EGP)" },
    { value: "ERN", label: "Eritrean Nakfa (ERN)" },
    { value: "ETB", label: "Ethiopian Birr (ETB)" },
    { value: "FJD", label: "Fijian Dollar (FJD)" },
    { value: "GEL", label: "Georgian Lari (GEL)" },
    { value: "GHS", label: "Ghanaian Cedi (GHS)" },
    { value: "GIP", label: "Gibraltar Pound (GIP)" },
    { value: "GMD", label: "Gambian Dalasi (GMD)" },
    { value: "GNF", label: "Guinean Franc (GNF)" },
    { value: "GTQ", label: "Guatemalan Quetzal (GTQ)" },
    { value: "HKD", label: "Hong Kong Dollar (HK$)" },
    { value: "HNL", label: "Honduran Lempira (HNL)" },
    { value: "HRK", label: "Croatian Kuna (HRK)" },
    { value: "HTG", label: "Haitian Gourde (HTG)" },
    { value: "HUF", label: "Hungarian Forint (HUF)" },
    { value: "IDR", label: "Indonesian Rupiah (IDR)" },
    { value: "ILS", label: "Israeli New Shekel (₪)" },
    { value: "INR", label: "Indian Rupee (₹)" },
    { value: "IQD", label: "Iraqi Dinar (IQD)" },
    { value: "IRR", label: "Iranian Rial (IRR)" },
    { value: "ISK", label: "Icelandic Króna (ISK)" },
    { value: "JMD", label: "Jamaican Dollar (JMD)" },
    { value: "JOD", label: "Jordanian Dinar (JOD)" },
    { value: "KES", label: "Kenyan Shilling (KES)" },
    { value: "KGS", label: "Kyrgyzstani Som (KGS)" },
    { value: "KHR", label: "Cambodian Riel (KHR)" },
    { value: "KMF", label: "Comorian Franc (KMF)" },
    { value: "KRW", label: "South Korean Won (₩)" },
    { value: "KWD", label: "Kuwaiti Dinar (KWD)" },
    { value: "KZT", label: "Kazakhstani Tenge (KZT)" },
    { value: "LAK", label: "Lao Kip (LAK)" },
    { value: "LBP", label: "Lebanese Pound (LBP)" },
    { value: "LKR", label: "Sri Lankan Rupee (LKR)" },
    { value: "LRD", label: "Liberian Dollar (LRD)" },
    { value: "LSL", label: "Lesotho Loti (LSL)" },
    { value: "LYD", label: "Libyan Dinar (LYD)" },
    { value: "MAD", label: "Moroccan Dirham (MAD)" },
    { value: "MDL", label: "Moldovan Leu (MDL)" },
    { value: "MGA", label: "Malagasy Ariary (MGA)" },
    { value: "MKD", label: "Macedonian Denar (MKD)" },
    { value: "MMK", label: "Myanmar Kyat (MMK)" },
    { value: "MNT", label: "Mongolian Tögrög (MNT)" },
    { value: "MOP", label: "Macanese Pataca (MOP)" },
    { value: "MRU", label: "Mauritanian Ouguiya (MRU)" },
    { value: "MUR", label: "Mauritian Rupee (MUR)" },
    { value: "MVR", label: "Maldivian Rufiyaa (MVR)" },
    { value: "MWK", label: "Malawian Kwacha (MWK)" },
    { value: "MXN", label: "Mexican Peso (MX$)" },
    { value: "MYR", label: "Malaysian Ringgit (RM)" },
    { value: "MZN", label: "Mozambican Metical (MZN)" },
    { value: "NAD", label: "Namibian Dollar (NAD)" },
    { value: "NGN", label: "Nigerian Naira (₦)" },
    { value: "NIO", label: "Nicaraguan Córdoba (NIO)" },
    { value: "NOK", label: "Norwegian Krone (NOK)" },
    { value: "NPR", label: "Nepalese Rupee (NPR)" },
    { value: "OMR", label: "Omani Rial (OMR)" },
    { value: "PAB", label: "Panamanian Balboa (PAB)" },
    { value: "PEN", label: "Peruvian Sol (PEN)" },
    { value: "PGK", label: "Papua New Guinean Kina (PGK)" },
    { value: "PHP", label: "Philippine Peso (₱)" },
    { value: "PKR", label: "Pakistani Rupee (₨)" },
    { value: "PLN", label: "Polish Złoty (PLN)" },
    { value: "PYG", label: "Paraguayan Guarani (PYG)" },
    { value: "QAR", label: "Qatari Riyal (QAR)" },
    { value: "RON", label: "Romanian Leu (RON)" },
    { value: "RSD", label: "Serbian Dinar (RSD)" },
    { value: "RUB", label: "Russian Ruble (₽)" },
    { value: "RWF", label: "Rwandan Franc (RWF)" },
    { value: "SAR", label: "Saudi Riyal (SAR)" },
    { value: "SCR", label: "Seychellois Rupee (SCR)" },
    { value: "SDG", label: "Sudanese Pound (SDG)" },
    { value: "SGD", label: "Singapore Dollar (S$)" },
    { value: "SLL", label: "Sierra Leonean Leone (SLL)" },
    { value: "SOS", label: "Somali Shilling (SOS)" },
    { value: "SRD", label: "Surinamese Dollar (SRD)" },
    { value: "SSP", label: "South Sudanese Pound (SSP)" },
    { value: "SYP", label: "Syrian Pound (SYP)" },
    { value: "SZL", label: "Swazi Lilangeni (SZL)" },
    { value: "THB", label: "Thai Baht (฿)" },
    { value: "TJS", label: "Tajikistani Somoni (TJS)" },
    { value: "TMT", label: "Turkmenistani Manat (TMT)" },
    { value: "TND", label: "Tunisian Dinar (TND)" },
    { value: "TOP", label: "Tongan Paʻanga (TOP)" },
    { value: "TRY", label: "Turkish Lira (₺)" },
    { value: "TTD", label: "Trinidad and Tobago Dollar (TTD)" },
    { value: "TWD", label: "New Taiwan Dollar (NT$)" },
    { value: "TZS", label: "Tanzanian Shilling (TZS)" },
    { value: "UAH", label: "Ukrainian Hryvnia (₴)" },
    { value: "UGX", label: "Ugandan Shilling (UGX)" },
    { value: "UYU", label: "Uruguayan Peso (UYU)" },
    { value: "UZS", label: "Uzbekistani Som (UZS)" },
    { value: "VES", label: "Venezuelan Bolívar (VES)" },
    { value: "VND", label: "Vietnamese Đồng (₫)" },
    { value: "VUV", label: "Vanuatu Vatu (VUV)" },
    { value: "WST", label: "Samoan Tala (WST)" },
    { value: "XAF", label: "Central African CFA Franc (XAF)" },
    { value: "XCD", label: "East Caribbean Dollar (XCD)" },
    { value: "XOF", label: "West African CFA Franc (XOF)" },
    { value: "YER", label: "Yemeni Rial (YER)" },
    { value: "ZAR", label: "South African Rand (R)" },
    { value: "ZMW", label: "Zambian Kwacha (ZMW)" },
    { value: "ZWL", label: "Zimbabwean Dollar (ZWL)" },
  ];
  