/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import DataList from "@/components/shared/dataTable/DataList";

interface Column {
  header: string;
  accessor: string;
  searchable?: boolean;
  fixed?: "left" | "right";
  width?: string;
  cell?: (row: any) => React.ReactNode;
  headerClassName?: string;
  cellClassName?: string;
}

const creativeData = [
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
  {
    id: 1,
    name: "Creative Asset 1",
    offers: "Offer A",
    partners: "Partner X",
    creative: "Banner_728x90.jpg",
    preview: "https://example.com/preview/banner_728x90.jpg",
    download: "https://example.com/download/banner_728x90.jpg",
    created: "2025-01-01",
    modified: "2025-05-01",
    action: "Edit",
  },
];

const creativeColumns: Column[] = [
  {
    header: "ID",
    accessor: "id",
    searchable: true,
    fixed: "left",
    width: "80px",
  },
  { header: "Name", accessor: "name", searchable: true },
  { header: "Offers", accessor: "offers", searchable: true },
  { header: "Partners", accessor: "partners", searchable: true },
  { header: "Creative", accessor: "creative", searchable: true },
  {
    header: "Preview",
    accessor: "preview",
    searchable: false,
    width: "300px",
    cell: (row: { preview: string }) => (
      <a
        href={row.preview}
        target="_blank"
        rel="noopener noreferrer"
        className="text-blue-600 underline"
      >
        Preview
      </a>
    ),
  },
  {
    header: "Download",
    accessor: "download",
    searchable: false,
    width: "300px",
    cell: (row: { download: string }) => (
      <a
        href={row.download}
        target="_blank"
        rel="noopener noreferrer"
        className="text-blue-600 underline"
      >
        Download
      </a>
    ),
  },
  { header: "Created", accessor: "created", searchable: false },
  { header: "Modified", accessor: "modified", searchable: false },
  {
    header: "Action",
    accessor: "action",
    searchable: false,
    fixed: "right",
    width: "100px",
  },
];

const Creative = () => (
  <DataList
    data={creativeData}
    columns={creativeColumns}
    addLinkLabel="+ Add Creative"
    showColumnToggle={true}
    showSearchBar={true}
    showfilter={false}
    addLink="/admin/offers/traffic-control/add"
  />
);

export default Creative;
