/* eslint-disable @typescript-eslint/no-explicit-any */
// import React from "react";

"use client";

import BoxAccordion, {
  BoxContent,
  BoxHeader,
} from "@/components/shared/boxAccordion/BoxAccordion";
import DataList from "@/components/shared/dataTable/DataList";
import FlexRow from "@/components/shared/responsibeForm/FlexRow";
interface Column {
  header: string;
  accessor: string;
  searchable?: boolean;
  fixed?: "left" | "right";
  width?: string;
  cell?: (row: any) => React.ReactNode;
  headerClassName?: string;
  cellClassName?: string;
}
const InvoiceListData = [
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
  {
    id: 1,
    invoiceId: "INV-001",
    partner: "Partner A",
    status: "Pending",
    visibility: "Private",
    paymentTerms: "Net 30",
    paymentMethod: "Bank Transfer",
    isPayable: true,
    startDate: "2025-05-01",
    endDate: "2025-05-31",
    amount: "$1,200.00",
    publicNotes: "Expected to clear within 30 days",
    internalNotes: "Partner has good history",
    dateCreated: "2025-05-01",
    lastModified: "2025-05-20",
    action: "Review",
  },
];

const adjustmentColumns: Column[] = [
  {
    header: "Invoice ID",
    accessor: "invoiceId",
    searchable: true,
    fixed: "left",
  },
  {
    header: "Partner",
    accessor: "partner",
    searchable: true,
  },
  {
    header: "Status",
    accessor: "status",
    searchable: true,
  },
  {
    header: "Visibility",
    accessor: "visibility",
    searchable: true,
  },
  {
    header: "Payment Terms",
    accessor: "paymentTerms",
    searchable: true,
  },
  {
    header: "Payment Method",
    accessor: "paymentMethod",
    searchable: true,
  },
  {
    header: "Is Payable",
    accessor: "isPayable",
    searchable: false,
    cell: (row: any) => (row.isPayable ? "Yes" : "No"),
  },
  {
    header: "Start Date",
    accessor: "startDate",
    searchable: false,
  },
  {
    header: "End Date",
    accessor: "endDate",
    searchable: false,
  },
  {
    header: "Amount",
    accessor: "amount",
    searchable: false,
  },
  {
    header: "Public Notes",
    accessor: "publicNotes",
    searchable: true,
    width: "200px",
  },
  {
    header: "Internal Notes",
    accessor: "internalNotes",
    searchable: true,
  },
  {
    header: "Date Created",
    accessor: "dateCreated",
    searchable: false,
  },
  {
    header: "Last Modification",
    accessor: "lastModified",
    searchable: false,
  },
  {
    header: "Action",
    accessor: "action",
    searchable: false,
    fixed: "right",
    width: "100px",
  },
];

const InvoiceList = () => {
  return (
    <>
      <BoxAccordion>
        <BoxHeader collapsible={false} className="bg-blue-50">
          <h2 className="text-sm font-base py-3">Invoice List</h2>
        </BoxHeader>
        <BoxContent>
          <FlexRow cols={{ base: 3, md: 6, lg: 12 }} gap={4}>
            <div className="flex flex-col items-center justify-center py-5">
              <h1 className="uppercase">Billed Amount</h1>
              <h1 className="text-2xl">$0.00</h1>
            </div>
            <div className="flex flex-col items-center justify-center py-5">
              <h1 className="uppercase">Billed Amount</h1>
              <h1 className="text-2xl">$0.00</h1>
            </div>
            <div className="flex flex-col items-center justify-center py-5">
              <h1 className="uppercase">Billed Amount</h1>
              <h1 className="text-2xl">$0.00</h1>
            </div>
          </FlexRow>
        </BoxContent>
      </BoxAccordion>
      <DataList
        data={InvoiceListData}
        columns={adjustmentColumns}
        addLinkLabel="+ Add Adjustment"
      />
    </>
  );
};
export default InvoiceList;
